[package]
name = "cuda-over-ip-client"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
cuda-over-ip-protocol = {path = "../protocol"}
prost = "0.13.3"
byteorder = "1.5.0"
static_init = "1.0.3"
